/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { EngineerService } from "../engineer.service";
import { EngineerCreateInput } from "./EngineerCreateInput";
import { Engineer } from "./Engineer";
import { EngineerFindManyArgs } from "./EngineerFindManyArgs";
import { EngineerWhereUniqueInput } from "./EngineerWhereUniqueInput";
import { EngineerUpdateInput } from "./EngineerUpdateInput";

export class EngineerControllerBase {
  constructor(protected readonly service: EngineerService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Engineer })
  async createEngineer(
    @common.Body() data: EngineerCreateInput
  ): Promise<Engineer> {
    return await this.service.createEngineer({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Engineer] })
  @ApiNestedQuery(EngineerFindManyArgs)
  async engineers(@common.Req() request: Request): Promise<Engineer[]> {
    const args = plainToClass(EngineerFindManyArgs, request.query);
    return this.service.engineers({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Engineer })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async engineer(
    @common.Param() params: EngineerWhereUniqueInput
  ): Promise<Engineer | null> {
    const result = await this.service.engineer({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Engineer })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateEngineer(
    @common.Param() params: EngineerWhereUniqueInput,
    @common.Body() data: EngineerUpdateInput
  ): Promise<Engineer | null> {
    try {
      return await this.service.updateEngineer({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Engineer })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteEngineer(
    @common.Param() params: EngineerWhereUniqueInput
  ): Promise<Engineer | null> {
    try {
      return await this.service.deleteEngineer({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
